# Wayle configuration file

[general]
font-sans = "JetBrainsMono Nerd Font"
font-mono = "JetBrainsMono Nerd Font"

[bar]
scale = 0.85
module-gap = 1.2
background-opacity = 100
border-color = "fg-subtle"
button-variant = "basic"
button-bg-opacity = 0
button-icon-size = 0.699999988079071
button-label-weight = "bold"
button-label-padding = 0.550000011920929
button-rounding = "none"
button-gap = 0.800000011920929
button-group-module-gap = 0.0
button-group-background = "transparent"
button-group-rounding = "none"

[[bar.layout]]
monitor = "*"
show = true
left = [
  "hyprland-workspaces",
  { name = "group", modules = [
    "custom-power",
    "custom-reboot",
    "custom-lock",
  ] },
  "custom-uptime",
  "media",
]
center = ["window-title"]
right = [
  "cpu",
  "network",
  "hyprsunset",
  { name = "group", modules = [
    "volume",
    "microphone",
  ] },
  "systray",
  "weather",
  "clock",
  "notifications",
]

[styling]
rounding = "none"

[styling.palette]
bg = "#11111b"
surface = "#181825"
elevated = "#1e1e2e"
fg = "#cdd6f4"
fg-muted = "#bac2de"
primary = "#b4befe"
red = "#f38ba8"
yellow = "#f9e2af"
green = "#a6e3a1"
blue = "#74c7ec"

[modules.clock]
format = "%H:%M"
icon-show = true
dropdown-show-seconds = true
icon-color = "#f5c2e7"
label-color = "#f5c2e7"
right-click = ""

[modules.notifications]
icon-name = "ld-bell-symbolic"
icon-unread = "ld-bell-dot-symbolic"
icon-dnd = "ld-bell-off-symbolic"

[modules.cpu]
border-color = "#94e2d5"
icon-color = "#94e2d5"
icon-bg-color = "#94e2d5"
label-color = "#94e2d5"
left-click = "kitty --detach btop"

[modules.window-title]
format = "{{ app }}"
left-click = "rofi -show window"

[modules.hyprland-workspaces]
label-size = 0.90
active-indicator = "underline"
app-icons-show = true
icon-size = 0.75
label-use-name = true
display-mode = "label"
show-special = true

[modules.hyprland-workspaces.workspace-map]
-98 = { label = "S", icon = "ld-scratch-symbolic", active-color = "accent" }

[[modules.custom]]
id = "uptime"
command = "~/.config/wayle/scripts/uptime.sh"
interval-ms = 5000
icon-name = "ld-arrow-up"
format = "{{ output }}"
left-click = "kitty --detach --hold fastfetch"


[[modules.custom]]
id = "power"
icon-name = "ld-power"
icon-color = "red"
left-click = "systemctl poweroff"

[[modules.custom]]
id = "reboot"
icon-name = "ld-refresh-cw"
icon-color = "green"
left-click = "systemctl reboot"

[[modules.custom]]
id = "lock"
icon-name = "ld-lock"
icon-color = "yellow"
left-click = "hyprlock"


[modules.media]
border-color = "accent"
icon-color = "accent"
icon-bg-color = "accent"
label-color = "accent"
label-max-length = 50
player-priority = ["quodlibet", "spotify", "mpd"]
players-ignored = ["chromium", "discord", "firefox"]
left-click = "wayle media play-pause"
right-click = "dropdown:media"

[modules.microphone]
border-color = "#fab387"
icon-color = "#fab387"
icon-bg-color = "#fab387"
label-color = "#fab387"
left-click = "wayle audio input-mute"
right-click = "dropdown:audio"
middle-click = "pavucontrol -t 4"
scroll-up = "wayle audio input-volume +5"
scroll-down = "wayle audio input-volume -5"

[modules.network]
border-color = "green"
icon-color = "green"
icon-bg-color = "green"
label-color = "green"

[modules.systray]
icon-scale = 0.800000011920929

[modules.volume]
border-color = "yellow"
icon-color = "yellow"
icon-bg-color = "yellow"
label-color = "yellow"
left-click = "wayle audio output-mute"
right-click = "dropdown:audio"
middle-click = "pavucontrol -t 3"
scroll-up = "wayle audio output-volume +5"
scroll-down = "wayle audio output-volume -5"

[modules.weather]
location = "Turku"
time-format = "24h"
icon-color = "#f2cdcd"
label-color = "#f2cdcd"
right-click = "firefox --new-window https://www.ilmatieteenlaitos.fi/saa/turku"

[wallpaper]
engine-enabled = false
