# This config is made for 2 external monitors (also your monitors busses could be different) 
# If you're using a laptop find the original default config here https://wiki.hypr.land/Hypr-Ecosystem/hypridle/#examples

general {
    lock_cmd = pidof hyprlock || hyprlock                                     # avoid starting multiple hyprlock instances.
    before_sleep_cmd = loginctl lock-session                                  # lock before suspend.
    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'  # to avoid having to press a key twice to turn on the display.
}

listener {
    timeout = 150                               # 2.5min
    # set monitor brightness to minimum, should work on monitors with ddc protocol (if ddcutil installed)                                 
    on-timeout = ddcutil setvcp 10 0 --bus 2 & ddcutil setvcp 10 0 --bus 3                               
    on-resume = ddcutil setvcp 10 100 --bus 2 & ddcutil setvcp 10 100 --bus 3   # monitor brightness restore.
}

listener {
    timeout = 300                                 # 5min
    on-timeout = loginctl lock-session            # lock screen when timeout has passed
}

# Unfortunately this section doesn't work on my main monitor since Samsung has managed to make
# the auto input detection option on their monitor broken. I'll see if I can fix it somehow. 
#listener {
#    timeout = 330                                                                                # 5.5min
#    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'                            # screen off when timeout has passed
#    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })' && ddcutil setvcp 10 100 --bus 2 && ddcutil setvcp 10 100 --bus 3
#    # screen on when activity is detected after timeout has fired.         
#}

listener {
    timeout = 1800                                # 30min
    on-timeout = systemctl suspend                # suspend pc
}